name: CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  ci:
    if: github.ref_type == 'branch'
    uses: brefwiz/shared-ci-workflows/.github/workflows/rust.yml@main
    with:
      run-coverage: true

  tag:
    if: github.ref == 'refs/heads/main'
    uses: brefwiz/shared-ci-workflows/.github/workflows/auto-tag.yml@main
    needs: ci
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}

  release:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    uses: brefwiz/shared-ci-workflows/.github/workflows/release-rust.yml@main
    with:
      crates: "groundwork"
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    permissions:
      contents: write
