name: Auto-tag

on:
  push:
    branches: [main]

jobs:
  tag:
    uses: brefwiz/shared-ci-workflows/.github/workflows/auto-tag.yml@main
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
